<a href="https://colab.research.google.com/github/Kwooley/TensorFlow_Tutorial/blob/main/tf_tut01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf


In [3]:
x = tf.constant([1,2,3])
print (x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [13]:
x = tf.zeros( [3]) 
print (x)

tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)


In [18]:
x = tf.int8
x = 20
print (x)

20


In [28]:
x = tf.constant([0,1,2,3,4,5], shape=(6,))
print (x)

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)


In [38]:
print (x[:])
print (x[1:])
print (x[:-2])
print (x[::-1])
print (x[::-2])

tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3], shape=(4,), dtype=int32)
tf.Tensor([5 4 3 2 1 0], shape=(6,), dtype=int32)
tf.Tensor([5 3 1], shape=(3,), dtype=int32)
